# Generated by Django 3.2.4 on 2021-06-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lanme',
            new_name='lname',
        ),
    ]
